name: nemo
class_name: nemo.models.nemo.NeMo

mesh_path: data/PASCAL3D+_release1.1/CAD_single/{:s}/01.off
num_noise: 5
max_group: 512
down_sample_rate: 8

transforms:
    - class_name: nemo.datasets.pascal3d.Normalize

training:
    separate_bank: true
    weight_noise: 0.005
    loss_reg_weight: 0.1
    train_accumulate: 10
    T: 0.07
    proj_mode: runtime_kp
    remove_near_mode: vert
    distance_thr: 0.1
    func_of_mesh: nemo.models.project_kp.func_multi_select

    weight_class: 10

    optimizer:
        class_name: torch.optim.Adam
        lr: 0.0001
        weight_decay: 0.0001

    scheduler:
        class_name: torch.optim.lr_scheduler.MultiStepLR
        milestones:
            - 400
            - 600
        gamma: 0.2

    kp_projecter:
        type: near
        down_rate: 1
        dist_thr: 0.01

inference:
    cameras:
        class_name: pytorch3d.renderer.PerspectiveCameras
        in_ndc: false
        image_size: -1
        principal_point: -1
        focal_length: 3000

    raster_settings:
        class_name: pytorch3d.renderer.RasterizationSettings
        blur_radius: 0.0
        faces_per_pixel: 1
        bin_size: 0

    rasterizer:
        class_name: pytorch3d.renderer.MeshRasterizer

backbone:
    class_name: nemo.models.keypoint_representation_net.NetE2E
    net_type: resnetext
    local_size:
        - 1
        - 1
    noise_on_mask: true
    output_dimension: 128
    reduce_function: None
    pretrain: true
    n_noise_points: 5

memory_bank:
    class_name: nemo.models.feature_banks.FeatureBankNeMo
    input_size: 128
    K: 1
    momentum: 0.96
