dataset: config/datasets/pascal3d.yaml
model: config/models/nemo.yaml

task: 3d_pose_estimation

training:
    batch_size: 48
    workers: 0
    total_epochs: 800
    log_interval: 1
    ckpt_interval: 200
    visualize_training_data: false
    remove_no_bg: 8

inference:
    loss: nemo.models.solve_pose.loss_fg_bg

    search_translation: false
    optimize_translation: false

    px_sample:
        min: 0.0
        max: 0.0
        num: 1
    py_sample:
        min: 0.0
        max: 0.0
        num: 1
    azim_sample:
        min_pi: 0.0
        max_pi: 2.0
        num: 12
    elev_sample:
        min_pi: -0.1667
        max_pi: 0.3333
        num: 4
    theta_sample:
        min_pi: -0.1667
        max_pi: 0.1667
        num: 3
    dist_sample:
        min: 4.0
        max: 6.0
        num: 3

    min_distance: 2
    pre_rendering_thr: 80
    blur_radius: 0.0
    inter_mode: bilinear
    epochs: 300
    translation_scale: 0.1

    optimizer:
        class_name: torch.optim.Adam
        lr: 0.05
        betas:
            - 0.4
            - 0.6

    scheduler:
        class_name: torch.optim.lr_scheduler.ExponentialLR
        gamma: 0.2
